# Generated by Django 6.0.3 on 2026-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
