# Generated by Django 6.0.3 on 2026-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_property_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_tier',
            field=models.CharField(choices=[('trial', 'Trial (2 Listings)'), ('standard', 'Standard (10 Listings)'), ('premium', 'Premium (50 Listings)'), ('ultimate', 'Ultimate (Unlimited)')], default='trial', max_length=20),
        ),
    ]
