# Generated by Django 6.0.3 on 2026-04-30 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_inquiry_inquirymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
