# Generated by Django 6.0.3 on 2026-05-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_subscriptiontransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('payment', 'Payment'), ('subscription', 'Subscription'), ('adjustment', 'Adjustment'), ('topup', 'Wallet Top-up'), ('withdrawal', 'Withdrawal')], max_length=20),
        ),
    ]
